### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by yasgreen93** [hex-digital/vue-accessible-datepicker#11]
#### **Part 1:**
- [x] Clicking/enter on calendar icon opens calendar. Focus is put immediately on the selected date.
- [x] Navigation of dates is with arrow keys.
- [x] Esc closes the datepicker.
- [x] Using right and left arrows takes you through each _**date**_ in sequential order. When reaching beginning/end of the month it goes to the previous/next month.
- [x] Using up and down arrows takes you through each _**week**_ in sequential order. When reaching beginning/end of the month it goes to the previous/next month.

#### **Part 2:**
- [x] Wrapper element of datepicker needs: `role="application"` and `aria-label="Calendar view date-picker"`
- [x] Previous month button labels and titles etc:
```html
<a
  class="ui-datepicker-prev ui-corner-all"
  data-handler="prev"
  data-event="click"
  title="Prev"
  href="javascript:void(0)"
  role="button"
>
    <span class="ui-icon ui-icon-circle-triangle-w">Previous Month, November 2019</span>
</a>
```
- [x] Next month button labels and titles etc:
```html
<a
  class="ui-datepicker-next ui-corner-all"
  data-handler="next"
  data-event="click"
  title="Next"
  href="javascript:void(0)"
  role="button"
>
  <span class="ui-icon ui-icon-circle-triangle-e">Next Month, January 2020</span>
</a>
```
- [x] Weekdays need `title="Friday" ` for example.
- [x] Individual date labels and titles etc:
```html
<td
  class=" "
  data-handler="selectDay"
  data-event="click"
  data-month="10"
  data-year="2019"
>
  <a class="ui-state-default" href="#" role="button" aria-label="1 November 2019 Friday">1</a></td>
```
